### ISSUE TITLE
Add link to GitHub repo in docs

### ISSUE THREAD

**Issue by edxu96** [edxu96/pf_impedance#12]
In https://edxu96.github.io/pf_impedance/ , there is no icon or link directed to this repository. There is probably an option in `documentation/conf.py`.

**Comment by dgabriel123** [comment]
Hello @edxu96 do you mean just adding "https://github.com/edxu96/pf_impedance" to the README, or do you have something different in mind?

**Comment by edxu96** [comment]
@dgabriel123 Hi, thanks for checking the repo. I just updated this issue.

I uploaded part of my master thesis code today, so it is not mature yet. Will finish all the tests, add GitHub action tomorrow. Besides, I got several pages equations for detailed model formulation, which will be integrated in coming days. Hope you like it.

**Comment by edxu96** [comment]
### To Do

- [x] [`sphinx.ext.viewcode`](https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html)
